#!/usr/bin/env bash
if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ ! -d /root/.npm ]; then
    mkdir /root/.npm
    chown -R sail:sail "/root/.npm"
fi

# Clear out all the Laravel caches
/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan view:clear
/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan config:clear
/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan route:clear

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
